app = "explorehere-topo-api"
primary_region = "iad"

[build]
  dockerfile = "docker/Dockerfile"

[env]
  PORT = "5000"

[[mounts]]
  source = "data"
  destination = "/app/data"

[[services]]
  protocol = "tcp"
  internal_port = 5000

  [[services.ports]]
    port = 80
    handlers = ["http"]

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20

  [[services.tcp_checks]]
    interval = "10s"
    timeout = "2s"
    restart_limit = 0
